spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/TODO?serverTimezone=Asia/Seoul
    username: todayssky
    password: 1113
  jpa:
    hibernate:
      ddl-auto: none # table auto create
    show-sql: true # SQL Log
    properties:
      hibernate:
        format_sql: # SQL pretty print
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
